language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t ivankhokhlov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ivankhokhlov/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region:  "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-300259718964"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY